<a href="https://colab.research.google.com/github/Prashanth-557/ML-Training/blob/main/Day12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df=sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df.sample(5)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6069,2019-03-14 19:39:32,2019-03-14 20:01:50,1,3.86,18.0,3.96,0.00,23.76,green,credit card,Astoria,LaGuardia Airport,Queens,Queens
2960,2019-03-07 02:05:11,2019-03-07 02:20:48,1,5.21,17.0,6.24,0.00,27.04,yellow,credit card,Midtown South,Old Astoria,Manhattan,Queens
5063,2019-03-13 21:35:04,2019-03-13 22:22:02,1,18.62,56.0,0.00,2.64,59.94,yellow,credit card,Lower East Side,Van Cortlandt Village,Manhattan,Bronx
4637,2019-03-01 18:36:55,2019-03-01 18:39:29,1,0.80,4.5,1.75,0.00,10.55,yellow,credit card,Lenox Hill West,Yorkville West,Manhattan,Manhattan
126,2019-03-13 08:46:04,2019-03-13 08:58:57,1,1.53,10.0,2.66,0.00,15.96,yellow,credit card,Lincoln Square West,Upper West Side North,Manhattan,Manhattan

In [ ]:
df.tail(5)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df.head(5)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
df['color'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [ ]:
df['color']

0       yellow
1       yellow
2       yellow
3       yellow
4       yellow
         ...
6428     green
6429     green
6430     green
6431     green
6432     green
Name: color, Length: 6433, dtype: object

In [ ]:
df['color'].isnull().sum()

0

In [ ]:
df['color'].isnull().sum()

0

In [ ]:
df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [ ]:
df['payment']

SyntaxError: invalid syntax (<ipython-input-10-38e9e33c87a8>, line 1)

In [ ]:
(44/6433)*100

0.6839732628633608

In [ ]:
df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [ ]:
df.shape[0]

6433

In [ ]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

missing data handling
1) Imputation (fill in the blanks)
   1)Stastical measures
   2)Parameter
2) Delete Data
  rows
  coloumns

In [15]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [20]:
a=df.drop('tolls',axis=1)

In [17]:
df.drop('pickup_zone',axis=1,inplace=True)

In [23]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [21]:
a

,pickup,dropoff,passengers,distance,fare,tip,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [24]:
df.drop(['color','payment','total'],axis=1,inplace=True)

In [25]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,Windsor Terrace,Brooklyn,Brooklyn

In [26]:
df.drop([1,2,3,4],axis=0,inplace=True)

In [27]:
df.drop([6428,6429,6430],axis=0,inplace=True)

In [28]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.00,2.15,0.0,UN/Turtle Bay South,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.50,2.16,0.0,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.00,2.00,0.0,Two Bridges/Seward Park,Manhattan,Manhattan
7,2019-03-22 12:47:13,2019-03-22 12:58:17,0,1.40,8.50,0.00,0.0,Flatiron,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.00,1.00,0.0,Midtown Center,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,East New York,Brooklyn,Brooklyn
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.50,0.50,0.0,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.0,East Harlem South,Bronx,Manhattan
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.00,0.00,0.0,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.0,Windsor Terrace,Brooklyn,Brooklyn

In [37]:
a=np.random.randint(10,50,15)
a

array([16, 34, 24, 21, 47, 36, 14, 48, 19, 13, 38, 38, 37, 46, 14])

In [38]:
a[a>20]

array([34, 24, 21, 47, 36, 48, 38, 38, 37, 46])

In [39]:
a[a>40]

array([47, 48, 46])

In [40]:
a[3]

21

In [41]:
df.iloc[2]

pickup                 2019-03-26 21:07:31
dropoff                2019-03-26 21:17:29
passengers                               1
distance                              3.65
fare                                  13.0
tip                                    2.0
tolls                                  0.0
dropoff_zone       Two Bridges/Seward Park
pickup_borough                   Manhattan
dropoff_borough                  Manhattan
Name: 6, dtype: object

In [42]:
df.iloc[6273]

pickup                          2019-03-17 14:06:48
dropoff                         2019-03-17 14:21:25
passengers                                        2
distance                                        2.4
fare                                           12.0
tip                                             0.0
tolls                                           0.0
dropoff_zone       East Concourse/Concourse Village
pickup_borough                            Manhattan
dropoff_borough                               Bronx
Name: 6277, dtype: object

In [43]:
df=sns.load_dataset('taxis')

In [44]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

In [47]:
df[df['color']=='yellow']

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5446,2019-03-11 21:19:42,2019-03-11 21:29:23,1,2.09,9.5,2.66,0.0,15.96,yellow,credit card,Battery Park City,Financial District North,Manhattan,Manhattan
5447,2019-03-20 18:09:46,2019-03-20 18:16:52,1,1.52,7.5,2.36,0.0,14.16,yellow,credit card,Upper West Side South,Upper East Side North,Manhattan,Manhattan
5448,2019-03-09 11:08:09,2019-03-09 11:18:03,1,2.05,9.5,2.56,0.0,15.36,yellow,credit card,Lenox Hill West,Upper West Side South,Manhattan,Manhattan
5449,2019-03-22 18:12:50,2019-03-22 18:22:05,1,1.07,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Penn Station/Madison Sq West,Manhattan,Manhattan
5450,2019-03-07 18:02:33,2019-03-07 18:13:32,1,1.80,9.0,1.33,0.0,14.63,yellow,credit card,Lincoln Square East,Upper West Side North,Manhattan,Manhattan

In [48]:
df[df['color']!='yellow']

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
5451,2019-03-24 15:05:22,2019-03-24 15:26:32,1,2.29,15.0,0.00,0.0,15.80,green,cash,Forest Hills,Corona,Queens,Queens
5452,2019-03-14 22:04:04,2019-03-14 22:10:00,1,0.80,5.5,0.00,0.0,6.80,green,credit card,Kew Gardens,Kew Gardens,Queens,Queens
5453,2019-03-29 18:12:27,2019-03-29 18:20:40,1,1.51,7.5,1.20,0.0,10.50,green,credit card,East Harlem North,East Harlem South,Manhattan,Manhattan
5454,2019-03-06 11:11:33,2019-03-06 11:15:15,1,0.45,4.5,0.00,0.0,5.30,green,cash,East Harlem North,East Harlem South,Manhattan,Manhattan
5455,2019-03-04 18:43:53,2019-03-04 18:46:50,1,0.61,4.0,0.00,0.0,5.80,green,cash,Carroll Gardens,Carroll Gardens,Brooklyn,Brooklyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [50]:
df[df['total']>50]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
42,2019-03-30 23:59:14,2019-03-30 23:59:17,1,0.00,80.0,20.08,0.00,100.38,yellow,credit card,NaN,NaN,NaN,NaN
56,2019-03-05 17:57:00,2019-03-05 18:45:25,2,19.59,52.0,0.00,5.76,65.56,yellow,credit card,JFK Airport,Upper East Side North,Queens,Manhattan
111,2019-03-15 10:56:56,2019-03-15 11:37:02,1,11.93,39.5,9.71,5.76,58.27,yellow,credit card,Times Sq/Theatre District,LaGuardia Airport,Manhattan,Queens
128,2019-03-06 19:29:56,2019-03-06 20:08:36,1,10.80,36.0,11.50,5.76,57.56,yellow,credit card,LaGuardia Airport,Clinton East,Queens,Manhattan
162,2019-03-06 17:36:48,2019-03-06 18:43:39,2,17.10,52.0,13.10,5.76,78.66,yellow,credit card,Midtown South,JFK Airport,Manhattan,Queens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362,2019-03-08 03:34:43,2019-03-08 04:20:37,1,21.37,62.5,0.00,5.76,69.56,green,credit card,Coney Island,Clinton West,Brooklyn,Manhattan
6393,2019-03-10 18:33:13,2019-03-10 19:32:38,1,0.00,71.2,0.00,0.00,72.00,green,credit card,Parkchester,Flatbush/Ditmas Park,Bronx,Brooklyn
6398,2019-03-17 13:07:29,2019-03-17 13:51:56,1,18.39,50.5,7.70,0.00,59.00,green,credit card,DUMBO/Vinegar Hill,JFK Airport,Brooklyn,Queens
6400,2019-03-22 17:41:23,2019-03-22 18:26:00,1,13.77,43.5,4.00,0.00,52.05,green,credit card,Jamaica,Little Italy/NoLiTa,Queens,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.00,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx

In [51]:
df[df['payment']=='cash']

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.0,0.0,9.3,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.0,17.8,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.0,0.0,13.8,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.0,0.0,14.8,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.0,0.0,16.8,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6420,2019-03-16 15:39:23,2019-03-16 15:46:18,2,1.20,7.0,0.0,0.0,7.8,green,cash,Central Harlem,Upper West Side North,Manhattan,Manhattan
6422,2019-03-22 20:17:35,2019-03-22 20:36:07,1,4.02,16.0,0.0,0.0,17.3,green,cash,Washington Heights South,Spuyten Duyvil/Kingsbridge,Manhattan,Bronx
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.0,0.0,0.0,9.3,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.0,0.0,20.0,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.0,0.0,17.3,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn

In [52]:
df['payment']=='cash'

0       False
1        True
2       False
3       False
4       False
        ...
6428    False
6429    False
6430     True
6431    False
6432    False
Name: payment, Length: 6433, dtype: bool

In [54]:
df[(df['payment']=='cash')&(df['color']=='yellow')]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.0,0.0,9.3,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.0,17.8,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.0,0.0,13.8,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.0,0.0,14.8,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.0,0.0,16.8,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5418,2019-03-24 09:01:29,2019-03-24 09:04:09,1,0.62,4.5,0.0,0.0,7.8,yellow,cash,East Village,SoHo,Manhattan,Manhattan
5421,2019-03-21 01:28:00,2019-03-21 01:34:21,5,1.69,7.5,0.0,0.0,8.8,yellow,cash,Elmhurst,Woodside,Queens,Queens
5435,2019-03-26 12:50:50,2019-03-26 12:53:29,1,0.43,4.0,0.0,0.0,7.3,yellow,cash,Sutton Place/Turtle Bay North,Sutton Place/Turtle Bay North,Manhattan,Manhattan
5440,2019-03-30 22:15:39,2019-03-30 22:37:45,2,3.26,15.5,0.0,0.0,19.3,yellow,cash,Lenox Hill East,East Chelsea,Manhattan,Manhattan
5444,2019-03-05 21:39:03,2019-03-05 21:49:12,5,1.31,8.0,0.0,0.0,11.8,yellow,cash,Clinton East,Midtown East,Manhattan,Manhattan

In [55]:
df[(df['payment']=='cash')&(df['total']>50)]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
302,2019-03-20 17:22:33,2019-03-20 18:07:19,1,17.01,52.0,0.0,5.76,65.56,yellow,cash,JFK Airport,Midtown East,Queens,Manhattan
1384,2019-03-09 17:58:55,2019-03-09 18:58:55,1,24.20,67.5,0.0,8.40,76.70,yellow,cash,JFK Airport,Riverdale/North Riverdale/Fieldston,Queens,Bronx
1406,2019-03-17 21:00:25,2019-03-17 21:43:21,1,18.20,52.0,0.0,5.76,61.06,yellow,cash,JFK Airport,East Village,Queens,Manhattan
1561,2019-03-09 13:07:03,2019-03-09 14:12:03,1,18.29,59.5,0.0,0.00,60.30,yellow,cash,JFK Airport,Downtown Brooklyn/MetroTech,Queens,Brooklyn
1657,2019-03-13 09:56:58,2019-03-13 10:49:35,1,17.10,52.0,0.0,0.00,55.30,yellow,cash,Midtown Center,JFK Airport,Manhattan,Queens
1726,2019-03-03 21:28:18,2019-03-03 21:57:44,2,18.47,52.0,0.0,0.00,52.80,yellow,cash,JFK Airport,Long Island City/Hunters Point,Queens,Queens
1774,2019-03-29 16:48:18,2019-03-29 16:56:31,2,1.89,52.0,0.0,5.76,65.56,yellow,cash,Long Island City/Hunters Point,Murray Hill,Queens,Manhattan
1791,2019-03-06 19:51:40,2019-03-06 20:30:31,1,22.47,59.5,0.0,5.76,67.06,yellow,cash,JFK Airport,Woodlawn/Wakefield,Queens,Bronx
1867,2019-03-28 17:19:20,2019-03-28 18:38:20,0,21.10,52.0,0.0,5.76,65.56,yellow,cash,Lincoln Square West,JFK Airport,Manhattan,Queens
2231,2019-03-11 10:17:31,2019-03-11 11:03:55,1,26.35,130.0,0.0,5.76,136.56,yellow,cash,East Harlem North,NaN,Manhattan,NaN
2311,2019-03-23 15:54:39,2019-03-23 16:43:28,1,18.60,52.0,0.0,5.76,61.06,yellow,cash,West Chelsea/Hudson Yards,JFK Airport,Manhattan,Queens
2388,2019-03-27 15:06:32,2019-03-27 16:18:52,2,18.00,52.0,0.0,0.00,55.30,yellow,cash,JFK Airport,Midtown North,Queens,Manhattan
2402,2019-03-29 22:29:40,2019-03-29 22:54:28,3,19.20,84.0,0.0,0.00,85.30,yellow,cash,JFK Airport,NaN,Queens,NaN
2480,2019-03-03 17:06:07,2019-03-03 18:12:38,1,18.34,52.0,0.0,5.76,61.06,yellow,cash,JFK Airport,Clinton East,Queens,Manhattan
2551,2019-03-02 17:46:29,2019-03-02 18:20:10,1,17.28,52.0,0.0,5.76,61.06,yellow,cash,JFK Airport,Stuy Town/Peter Cooper Village,Queens,Manhattan
2777,2019-03-21 14:54:46,2019-03-21 16:06:29,1,20.14,52.0,0.0,5.76,61.06,yellow,cash,JFK Airport,Lenox Hill East,Queens,Manhattan
2905,2019-03-18 16:53:21,2019-03-18 17:41:48,1,24.57,78.0,0.0,5.76,85.56,yellow,cash,JFK Airport,NaN,Queens,NaN
2962,2019-03-14 23:37:21,2019-03-15 00:17:07,1,17.45,50.5,0.0,5.76,60.06,yellow,cash,Midtown Center,Howard Beach,Manhattan,Queens
3077,2019-03-14 02:45:24,2019-03-14 03:13:13,1,17.95,52.0,0.0,0.00,55.30,yellow,cash,JFK Airport,Midtown North,Queens,Manhattan
3095,2019-03-19 22:20:25,2019-03-19 22:20:38,1,0.00,52.0,0.0,5.76,61.06,yellow,cash,Midtown Center,Midtown Center,Manhattan,Manhattan
3249,2019-03-17 20:34:16,2019-03-17 21:15:49,1,20.90,52.0,0.0,5.76,58.56,yellow,cash,JFK Airport,Washington Heights North,Queens,Manhattan
3459,2019-03-08 14:51:23,2019-03-08 15:52:38,1,18.27,52.0,0.0,5.76,61.06,yellow,cash,JFK Airport,Midtown South,Queens,Manhattan
3523,2019-03-06 19:08:16,2019-03-06 19:53:16,1,18.30,52.0,0.0,5.76,65.56,yellow,cash,JFK Airport,Times Sq/Theatre District,Queens,Manhattan
3570,2019-03-22 12:46:38,2019-03-22 13:25:50,3,16.33,52.0,0.0,5.76,61.06,yellow,cash,Midtown East,JFK Airport,Manhattan,Queens
3640,2019-03-22 07:54:09,2019-03-22 09:05:13,1,16.42,52.0,0.0,12.50,67.80,yellow,cash,JFK Airport,Murray Hill,Queens,Manhattan
3661,2019-03-04 21:24:54,2019-03-04 21:55:07,1,21.30,79.5,0.0,0.00,80.80,yellow,cash,JFK Airport,NaN,Queens,NaN
3894,2019-03-29 04:52:30,2019-03-29 05:19:30,1,17.03,52.0,0.0,0.00,55.30,yellow,cash,Central Park,JFK Airport,Manhattan,Queens
3977,2019-03-15 16:45:55,2019-03-15 17:46:47,4,15.64,50.0,0.0,5.76,60.06,yellow,cash,LaGuardia Airport,Battery Park City,Queens,Manhattan
4050,2019-03-13 14:05:19,2019-03-13 15:01:16,6,33.76,143.5,0.0,0.00,144.30,yellow,cash,LaGuardia Airport,NaN,Queens,NaN
4057,2019-03-29 22:23:08,2019-03-29 22:52:37,5,15.14,52.0,0.0,5.76,61.06,yellow,cash,Jamaica,Upper West Side North,Queens,Manhattan
4075,2019-03-30 14:56:08,2019-03-30 15:49:32,5,17.14,52.0,0.0,0.00,55.30,yellow,cash,JFK Airport,Sutton Place/Turtle Bay North,Queens,Manhattan
4192,2019-03-08 08:19:28,2019-03-08 08:55:37,1,16.53,48.0,0.0,5.76,57.06,yellow,cash,Lincoln Square East,LaGuardia Airport,Manhattan,Queens
4484,2019-03-27 13:36:40,2019-03-27 14:34:04,6,18.94,59.5,0.0,5.76,68.56,yellow,cash,Morningside Heights,Flatlands,Manhattan,Brooklyn
4641,2019-03-31 21:03:02,2019-03-31 22:04:59,1,23.30,67.5,0.0,6.12,74.92,yellow,cash,JFK Airport,Mount Hope,Queens,Bronx
4776,2019-03-19 18:32:11,2019-03-19 19:19:45,1,19.29,52.0,0.0,0.00,59.80,yellow,cash,JFK Airport,Lincoln Square East,Queens,Manhattan
4870,2019-03-03 12:20:58,2019-03-03 12:55:58,6,19.94,52.0,0.0,5.76,61.06,yellow,cash,Upper East Side South,JFK Airport,Manhattan,Queens
4885,2019-03-08 23:05:31,2019-03-08 23:29:42,3,17.41,52.0,0.0,5.76,61.06,yellow,cash,JFK Airport,Murray Hill,Queens,Manhattan
5014,2019-03-28 18:49:50,2019-03-28 19:41:04,5,21.51,52.0,0.0,5.76,65.56,yellow,cash,JFK Airport,World Trade Center,Queens,Manhattan
5243,2019-03-13 12:07:26,2019-03-13 12:47:51,1,17.51,52.0,0.0,0.00,55.30,yellow,cash,East Chelsea,LaGuardia Airport,Manhattan,Queens
5364,2019-03-17 16:59:17,2019-03-17 18:04:08,2,36.70,150.0,0.0,24.02,174.82,yellow,cash,JFK Airport,JFK Airport,Queens,Queens
5648,2019-03-19 14:21:35,2019-03-19 15:51:28,2,33.46,150.0,0.0,18.90,169.70,green,cash,East Flushing,NaN,Queens,NaN
5678,2019-03-15 20:34:02,2019-03-15 20:34:10,1,0.00,52.0,0.0,0.00,52.80,green,cash,Downtown Brooklyn/MetroTech,Downtown Brooklyn/MetroTech,Brooklyn,Brooklyn

In [56]:
df[(df['payment']=='cash')|(df['color']=='yellow')&(df['total']>50)]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.0,0.0,9.3,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.0,17.8,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.0,0.0,13.8,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.0,0.0,14.8,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.0,0.0,16.8,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6420,2019-03-16 15:39:23,2019-03-16 15:46:18,2,1.20,7.0,0.0,0.0,7.8,green,cash,Central Harlem,Upper West Side North,Manhattan,Manhattan
6422,2019-03-22 20:17:35,2019-03-22 20:36:07,1,4.02,16.0,0.0,0.0,17.3,green,cash,Washington Heights South,Spuyten Duyvil/Kingsbridge,Manhattan,Bronx
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.0,0.0,0.0,9.3,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.0,0.0,20.0,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.0,0.0,17.3,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn